const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const menuSchema = new Schema({
    breakfastVegMon:{ type: String, required: true },
    breakfastVegTue:{ type: String, required: true },
    breakfastVegWed:{ type: String, required: true },
    breakfastVegThur:{ type: String, required: true },
    breakfastVegFri:{ type: String, required: true },
    breakfastVegSat:{ type: String, required: true },
    breakfastVegSun:{ type: String, required: true },
    breakfastNonVegMon:{ type: String, required: true },
    breakfastNonVegTue:{ type: String, required: true },
    breakfastNonVegWed:{ type: String, required: true },
    breakfastNonVegThur:{ type: String, required: true },
    breakfastNonVegFri:{ type: String, required: true },
    breakfastNonVegSat:{ type: String, required: true },
    breakfastNonVegSun:{ type: String, required: true },
    lunchVegMon:{ type: String, required: true },
    lunchVegTue:{ type: String, required: true },
    lunchVegWed:{ type: String, required: true },
    lunchVegThu:{ type: String, required: true },
    lunchVegFri:{ type: String, required: true },
    lunchVegSat:{ type: String, required: true },
    lunchVegSun:{ type: String, required: true },
    lunchNonVegMon:{ type: String, required: true },
    lunchNonVegTue:{ type: String, required: true },
    lunchNonVegWed:{ type: String, required: true },
    lunchNonVegThu:{ type: String, required: true },
    lunchNonVegFri:{ type: String, required: true },
    lunchNonVegSat:{ type: String, required: true },
    lunchNonVegSun:{ type: String, required: true },
    snacksVegMon:{ type: String, required: true },
    snacksVegTue:{ type: String, required: true },
    snacksVegWed:{ type: String, required: true },
    snacksVegThu:{ type: String, required: true },
    snacksVegFri:{ type: String, required: true },
    snacksVegSat:{ type: String, required: true },
    snacksVegSun:{ type: String, required: true },
    snacksNonVegMon:{ type: String, required: true },
    snacksNonVegTue:{ type: String, required: true },
    snacksNonVegWed:{ type: String, required: true },
    snacksNonVegThu:{ type: String, required: true },
    snacksNonVegFri:{ type: String, required: true },
    snacksNonVegSat:{ type: String, required: true },
    snacksNonVegSun:{ type: String, required: true },
    dinnerVegMon:{ type: String, required: true },
    dinnerVegTue:{ type: String, required: true },
    dinnerVegWed:{ type: String, required: true },
    dinnerVegThu:{ type: String, required: true },
    dinnerVegFri:{ type: String, required: true },
    dinnerVegSat:{ type: String, required: true },
    dinnerVegSun:{ type: String, required: true },
    dinnerNonVegMon:{ type: String, required: true },
    dinnerNonVegTue:{ type: String, required: true },
    dinnerNonVegWed:{ type: String, required: true },
    dinnerNonVegThu:{ type: String, required: true },
    dinnerNonVegFri:{ type: String, required: true },
    dinnerNonVegSat:{ type: String, required: true },
    dinnerNonVegSun:{ type: String, required: true },
})
module.exports = menu = mongoose.model('menu', menuSchema);
    
