const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const attendanceSchema = new Schema({
    breakfastVegMon:{ type: Number, default: 0 },
    breakfastVegTue:{  type: Number, default: 0 },
    breakfastVegWed:{  type: Number, default: 0  },
    breakfastVegThur:{  type: Number, default: 0  },
    breakfastVegFri:{  type: Number, default: 0},
    breakfastVegSat:{  type: Number, default: 0  },
    breakfastVegSun:{  type: Number, default: 0 },
    breakfastNonVegMon:{  type: Number, default: 0 },
    breakfastNonVegTue:{  type: Number, default: 0 },
    breakfastNonVegWed:{  type: Number, default: 0  },
    breakfastNonVegThur:{  type: Number, default: 0 },
    breakfastNonVegFri:{  type: Number, default: 0 },
    breakfastNonVegSat:{  type: Number, default: 0 },
    breakfastNonVegSun:{  type: Number, default: 0 },
    NoBreakfastMon:{  type: Number, default: 0 },
    NoBreakfastTue:{  type: Number, default: 0 },
    NoBreakfastWed:{  type: Number, default: 0  },
    NoBreakfastThur:{  type: Number, default: 0 },
    NoBreakfastFri:{  type: Number, default: 0 },
    NoBreakfastSat:{  type: Number, default: 0 },
    NoBreakfastSun:{  type: Number, default: 0 },
    lunchVegMon:{  type: Number, default: 0 },
    lunchVegTue:{  type: Number, default: 0 },
    lunchVegWed:{  type: Number, default: 0 },
    lunchVegThu:{  type: Number, default: 0 },
    lunchVegFri:{  type: Number, default: 0 },
    lunchVegSat:{  type: Number, default: 0 },
    lunchVegSun:{  type: Number, default: 0 },
    lunchNonVegMon:{  type: Number, default: 0 },
    lunchNonVegTue:{  type: Number, default: 0 },
    lunchNonVegWed:{  type: Number, default: 0 },
    lunchNonVegThu:{  type: Number, default: 0 },
    lunchNonVegFri:{  type: Number, default: 0 },
    lunchNonVegSat:{  type: Number, default: 0 },
    lunchNonVegSun:{  type: Number, default: 0 },
    NoLunchMon:{  type: Number, default: 0 },
    NoLunchTue:{  type: Number, default: 0 },
    NoLunchWed:{  type: Number, default: 0 },
    NoLunchThu:{  type: Number, default: 0 },
    NoLunchFri:{  type: Number, default: 0 },
    NoLunchSat:{  type: Number, default: 0 },
    NoLunchSun:{  type: Number, default: 0 },
    snacksVegMon:{  type: Number, default: 0 },
    snacksVegTue:{  type: Number, default: 0 },
    snacksVegWed:{  type: Number, default: 0 },
    snacksVegThu:{  type: Number, default: 0},
    snacksVegFri:{  type: Number, default: 0},
    snacksVegSat:{  type: Number, default: 0},
    snacksVegSun:{  type: Number, default: 0},
    snacksNonVegMon:{  type: Number, default: 0 },
    snacksNonVegTue:{  type: Number, default: 0},
    snacksNonVegWed:{  type: Number, default: 0 },
    snacksNonVegThu:{  type: Number, default: 0 },
    snacksNonVegFri:{  type: Number, default: 0 },
    snacksNonVegSat:{  type: Number, default: 0},
    snacksNonVegSun:{  type: Number, default: 0},
    NoSnacksMon:{  type: Number, default: 0 },
    NoSnacksTue:{  type: Number, default: 0 },
    NoSnacksWed:{  type: Number, default: 0 },
    NoSnacksThu:{  type: Number, default: 0},
    NoSnacksFri:{  type: Number, default: 0},
    NoSnacksSat:{  type: Number, default: 0},
    NoSnacksSun:{  type: Number, default: 0},
    dinnerVegMon:{  type: Number, default: 0},
    dinnerVegTue:{  type: Number, default: 0 },
    dinnerVegWed:{  type: Number, default: 0},
    dinnerVegThu:{  type: Number, default: 0 },
    dinnerVegFri:{  type: Number, default: 0},
    dinnerVegSat:{  type: Number, default: 0},
    dinnerVegSun:{  type: Number, default: 0 },
    dinnerNonVegMon:{  type: Number, default: 0},
    dinnerNonVegTue:{  type: Number, default: 0},
    dinnerNonVegWed:{ type: Number, default: 0},
    dinnerNonVegThu:{  type: Number, default: 0},
    dinnerNonVegFri:{  type: Number, default: 0},
    dinnerNonVegSat:{ type: Number, default: 0},
    dinnerNonVegSun:{  type: Number, default: 0 },
    NoDinnerMon:{  type: Number, default: 0},
    NoDinnerTue:{  type: Number, default: 0 },
    NoDinnerWed:{  type: Number, default: 0},
    NoDinnerThu:{  type: Number, default: 0 },
    NoDinnerFri:{  type: Number, default: 0},
    NoDinnerSat:{  type: Number, default: 0},
    NoDinnerSun:{  type: Number, default: 0 },
})
module.exports = attendance = mongoose.model('attendance', attendanceSchema);
    
